# Generated by Django 3.0.6 on 2020-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resource_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
